### ISSUE TITLE
'est_mags = mask_mags*spec_mags', could you give 'spec_mags' and 'spec_phase' calculation method?

### ISSUE THREAD

**Issue by laozhanger** [dangf15/DPT-FSNet#1]

**Comment by dangf15** [comment]
spec_mags = torch.sqrt(real ** 2+imag ** 2+1e-8)
 类似mask_mags的计算方式，在model.py的第225行后加一行 即可

**Comment by laozhanger** [comment]
那 spec_phase 的计算也是类似这样吗？
            spec_mags = (real ** 2 + imag ** 2) ** 0.5
            mask_mags = (mask_real ** 2 + mask_imag ** 2) ** 0.5
            mask_real_phase = mask_real / (mask_mags + 1e-8)
            mask_imag_phase = mask_imag / (mask_mags + 1e-8)
            mask_phase = torch.atan2(mask_imag_phase, mask_real_phase)
            
            real_phase = real / (spec_mags + 1e-8)
            imag_phase = imag / (spec_mags + 1e-8)
            spec_phase = torch.atan2(imag_phase, real_phase)

**Comment by laozhanger** [comment]
那 spec_phase 的计算也是类似这样吗？
            spec_mags = (real ** 2 + imag ** 2) ** 0.5
            mask_mags = (mask_real ** 2 + mask_imag ** 2) ** 0.5
            mask_real_phase = mask_real / (mask_mags + 1e-8)
            mask_imag_phase = mask_imag / (mask_mags + 1e-8)
            mask_phase = torch.atan2(mask_imag_phase, mask_real_phase)
            
            real_phase = real / (spec_mags + 1e-8)
            imag_phase = imag / (spec_mags + 1e-8)
            spec_phase = torch.atan2(imag_phase, real_phase)

**Comment by dangf15** [comment]
对的
